"""
Conversation States
"""

NEW = "NEW"

WAITING_FOR_DOCUMENT = "WAITING_FOR_DOCUMENT"

WAITING_FOR_DISTRICT = "WAITING_FOR_DISTRICT"

WAITING_FOR_DEPARTMENT = "WAITING_FOR_DEPARTMENT"

WAITING_FOR_OFFICE = "WAITING_FOR_OFFICE"

WAITING_FOR_ADDRESS = "WAITING_FOR_ADDRESS"

WAITING_FOR_PHOTO = "WAITING_FOR_PHOTO"

WAITING_FOR_CONFIRMATION = "WAITING_FOR_CONFIRMATION"

COMPLETED = "COMPLETED"
