#!/usr/bin/env python3
"""Janavani repository hygiene and generation-audit tool.

Read-only, standard-library-only audit. Findings are review candidates, not
automatic deletion instructions.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections import defaultdict
from pathlib import Path

SKIP_DIRS = {".git", ".venv", "venv", "node_modules", "__pycache__", ".pytest_cache"}
TEXT_SUFFIXES = {".py", ".yml", ".yaml", ".toml", ".json", ".md", ".txt", ".sh", ".js", ".ts", ".tsx", ".jsx", ".conf"}
CODE_SUFFIXES = {".py", ".js", ".ts", ".tsx", ".jsx", ".sh"}
CONFIG_NAMES = {"docker-compose.yml", "docker-compose.yaml", "nginx.conf"}
PLACEHOLDER_RE = re.compile(r"(?:TODO|FIXME|NotImplementedError|IMPLEMENT_ME|PLACEHOLDER|YOUR_[_A-Z]+)")
GENERATED_RE = re.compile(r"(?:DO NOT EDIT|generated by|auto-generated|AUTOGENERATED)", re.I)
ACTION_RE = re.compile(r"uses:\s*([^\s#]+)")
LEGACY_NAME_RE = re.compile(r"(?:^|[_-])(legacy|old|deprecated|backup|archive|v[0-9]+)(?:[_-]|\.|$)", re.I)
MIGRATION_RE = re.compile(r"(?:deprecated|deprecate|migration|migrate|replacement|replaced by|superseded|legacy)", re.I)
DEF_RE = re.compile(r"^\s*(?:async\s+)?(?:def|class)\s+([A-Za-z_][\w]*)", re.M)
SERVICE_RE = re.compile(r"^\s{2}([A-Za-z0-9_.-]+):\s*$", re.M)
UPSTREAM_RE = re.compile(r"(?:proxy_pass\s+https?://|proxy_pass\s+)([A-Za-z0-9_.-]+)(?::\d+)?", re.I)


def iter_files(root: Path):
    for path in root.rglob("*"):
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if path.is_file():
            yield path


def read_text(path: Path) -> str | None:
    if path.suffix.lower() not in TEXT_SUFFIXES:
        return None
    try:
        return path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return None


def normalized_code(content: str) -> str:
    lines = []
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        lines.append(re.sub(r"\s+", " ", stripped))
    return "\n".join(lines)


def confidence_from_count(count: int) -> str:
    if count >= 3:
        return "HIGH"
    if count == 2:
        return "MEDIUM"
    return "LOW"


def finding(category: str, path: str | list[str], signals: list[str], classification: str = "INVESTIGATE", confidence: str | None = None) -> dict[str, object]:
    return {"category": category, "path": path, "signals": signals, "confidence": confidence or confidence_from_count(len(signals)), "suggested_classification": classification, "destructive_action_allowed": False}


def main() -> int:
    parser = argparse.ArgumentParser(description="Read-only Janavani repository hygiene and generation audit")
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument("--json", action="store_true", dest="as_json", help="emit machine-readable JSON")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    findings: list[dict[str, object]] = []
    contents: dict[str, str] = {}
    hashes: dict[str, list[str]] = defaultdict(list)
    definitions: dict[str, list[str]] = defaultdict(list)

    for path in iter_files(root):
        rel = path.relative_to(root).as_posix()
        try:
            size = path.stat().st_size
        except OSError:
            continue
        if size == 0:
            findings.append(finding("EMPTY", rel, ["zero-byte file"], "INVESTIGATE", "HIGH")); continue
        content = read_text(path)
        if content is None: continue
        contents[rel] = content
        if not content.strip():
            findings.append(finding("EMPTY", rel, ["whitespace-only file"], "INVESTIGATE", "HIGH")); continue
        if PLACEHOLDER_RE.search(content): findings.append(finding("PLACEHOLDER", rel, ["placeholder marker"]))
        if GENERATED_RE.search(content): findings.append(finding("GENERATED", rel, ["generated-file marker"], "KEEP", "LOW"))
        if LEGACY_NAME_RE.search(path.name): findings.append(finding("LEGACY_NAMING_SIGNAL", rel, ["legacy-style filename"]))
        if MIGRATION_RE.search(content): findings.append(finding("MIGRATION_SIGNAL", rel, ["migration/deprecation language"]))

        if rel.startswith(".github/workflows/"):
            for match in ACTION_RE.finditer(content):
                action = match.group(1)
                if "@" in action and not re.fullmatch(r"[0-9a-fA-F]{40}", action.rsplit("@", 1)[1]):
                    findings.append(finding("MUTABLE_ACTION", rel, [f"mutable action reference: {action}"], "INVESTIGATE", "LOW"))
            if re.search(r"permissions:\s*\n(?:\s+\S+:\s*(?:write|write-all)\b|\s+contents:\s*write\b)", content, re.I):
                findings.append(finding("BROAD_PERMISSIONS", rel, ["workflow requests write permissions"], "INVESTIGATE", "LOW"))

        if path.suffix.lower() in CODE_SUFFIXES:
            normalized = normalized_code(content)
            if len(normalized) >= 200: hashes[hashlib.sha256(normalized.encode()).hexdigest()].append(rel)
            for name in DEF_RE.findall(content): definitions[name].append(rel)

    for paths in hashes.values():
        if len(paths) > 1: findings.append(finding("EXACT_DUPLICATE_CODE", paths, ["same normalized code content"], "CONVERGE", "MEDIUM"))

    stem_groups: dict[str, list[str]] = defaultdict(list)
    for rel in contents:
        p = Path(rel)
        if p.suffix.lower() in CODE_SUFFIXES:
            base = re.sub(r"(?:[_-](?:legacy|old|deprecated|backup|v\d+))+$", "", p.stem, flags=re.I)
            stem_groups[base.lower()].append(rel)
    for paths in stem_groups.values():
        if len(paths) < 2: continue
        for rel in paths:
            p = Path(rel); signals = []
            if LEGACY_NAME_RE.search(p.name): signals.append("legacy-style filename")
            if MIGRATION_RE.search(contents[rel]): signals.append("migration/deprecation language")
            siblings = [x for x in paths if x != rel]
            if siblings: signals.append("parallel code module with overlapping stem: " + ", ".join(sorted(siblings)))
            if len(signals) >= 2: findings.append(finding("LEGACY_GENERATION_CANDIDATE", rel, signals))

    for name, paths in definitions.items():
        unique_paths = sorted(set(paths))
        if len(unique_paths) > 1 and name not in {"main", "__init__"}:
            findings.append(finding("PARALLEL_DEFINITION_SIGNAL", unique_paths, [f"symbol defined in multiple files: {name}"], "INVESTIGATE", "MEDIUM"))

    for rel in list(contents):
        p = Path(rel)
        if p.suffix.lower() in CODE_SUFFIXES and LEGACY_NAME_RE.search(p.stem):
            refs = [o for o, c in contents.items() if o != rel and (p.stem in c or rel in c)]
            if refs: findings.append(finding("LEGACY_REFERENCED_SIGNAL", rel, ["legacy-style module has textual references: " + ", ".join(sorted(refs))], "INVESTIGATE", "MEDIUM"))

    for rel in contents:
        p = Path(rel)
        if p.suffix == ".py" and rel.startswith("scripts/") and not p.name.startswith(("__", "test")):
            refs = sum(1 for o in contents if o != rel and (p.stem in contents[o] or rel in contents[o]))
            if refs == 0: findings.append(finding("POTENTIAL_ORPHAN_SCRIPT", rel, ["no obvious textual reference"]))

    # Configuration-generation audit. This deliberately compares configuration
    # relationships rather than declaring a config file obsolete by age/name.
    compose_services: set[str] = set()
    canonical_runtime_refs: set[str] = set()
    for rel, content in contents.items():
        if Path(rel).name in CONFIG_NAMES or Path(rel).name.startswith("docker-compose"):
            if Path(rel).name.startswith("docker-compose"):
                compose_services.update(SERVICE_RE.findall(content))
            if Path(rel).name == "nginx.conf":
                upstreams = set(UPSTREAM_RE.findall(content))
                missing = sorted(u for u in upstreams if u not in compose_services and u not in {"localhost", "127.0.0.1"})
                if missing:
                    findings.append(finding("CONFIG_SERVICE_MISMATCH", rel, [f"nginx upstream/service not defined by compose services: {', '.join(missing)}"], "INVESTIGATE", "MEDIUM"))
                events = len(re.findall(r"^\s*events\s*\{", content, re.M))
                https = len(re.findall(r"^\s*http\s*\{", content, re.M))
                if events > 1: findings.append(finding("DUPLICATE_CONFIG_BLOCK", rel, [f"multiple nginx events blocks: {events}"], "CONVERGE", "HIGH"))
                if https > 1: findings.append(finding("DUPLICATE_CONFIG_BLOCK", rel, [f"multiple nginx http blocks: {https}"], "CONVERGE", "HIGH"))
        if rel.endswith("canonical_app.py"):
            canonical_runtime_refs.update(re.findall(r"from\s+(src\.[A-Za-z0-9_.]+)", content))

    payload = {"tool": "janavani_repo_audit", "version": "0.5", "root": str(root), "read_only": True, "legacy_generation_signals": True, "configuration_generation_signals": True, "classifications": ["KEEP", "CONVERGE", "ARCHIVE", "DELETE", "INVESTIGATE"], "findings": findings}
    if args.as_json:
        print(json.dumps(payload, indent=2)); return 0
    print("JANAVANI REPOSITORY HYGIENE + GENERATION AUDIT")
    print(f"Root: {root}\n" + "=" * 72)
    for item in findings:
        print(f"\n[{item['category']}] {item['path']}\n  Signals: {', '.join(item['signals'])}\n  Confidence: {item['confidence']}\n  Suggested classification: {item['suggested_classification']}")
    print(f"\nFindings: {len(findings)}\nNo files were modified.")
    print("All classifications are review guidance, not automatic deletion instructions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
