#!/usr/bin/env python3
"""Janavani repository hygiene audit.

Standard-library-only CLI for finding cleanup candidates without modifying files.
It reports empty files, placeholder-only source, generated markers, mutable GitHub
Actions references, and workflow files with unusually broad write permissions.

Usage: python scripts/janavani_repo_audit.py [ROOT]
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

SKIP_DIRS = {".git", ".venv", "venv", "node_modules", "__pycache__", ".pytest_cache"}
TEXT_SUFFIXES = {".py", ".yml", ".yaml", ".toml", ".json", ".md", ".txt", ".sh", ".js", ".ts", ".tsx", ".jsx"}
PLACEHOLDER_RE = re.compile(r"(?:TODO|FIXME|NotImplementedError|IMPLEMENT_ME|PLACEHOLDER|YOUR_[_A-Z]+)")
GENERATED_RE = re.compile(r"(?:DO NOT EDIT|generated by|auto-generated|AUTOGENERATED)", re.I)
ACTION_RE = re.compile(r"uses:\s*([^\s#]+)")


def files(root: Path):
    for path in root.rglob("*"):
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if path.is_file():
            yield path


def text(path: Path) -> str | None:
    if path.suffix.lower() not in TEXT_SUFFIXES:
        return None
    try:
        return path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return None


def main(root_arg: str = ".") -> int:
    root = Path(root_arg).resolve()
    findings: dict[str, list[str]] = {"EMPTY": [], "PLACEHOLDER": [], "GENERATED": [], "MUTABLE_ACTION": [], "BROAD_PERMISSIONS": []}

    for path in files(root):
        rel = path.relative_to(root).as_posix()
        try:
            if path.stat().st_size == 0:
                findings["EMPTY"].append(rel)
                continue
        except OSError:
            continue

        content = text(path)
        if content is None:
            continue
        stripped = content.strip()
        if not stripped:
            findings["EMPTY"].append(rel)
            continue
        if PLACEHOLDER_RE.search(content):
            findings["PLACEHOLDER"].append(rel)
        if GENERATED_RE.search(content):
            findings["GENERATED"].append(rel)

        if rel.startswith(".github/workflows/"):
            for match in ACTION_RE.finditer(content):
                action = match.group(1)
                if "@" in action:
                    ref = action.rsplit("@", 1)[1]
                    if not re.fullmatch(r"[0-9a-fA-F]{40}", ref):
                        findings["MUTABLE_ACTION"].append(f"{rel}: {action}")
            if re.search(r"permissions:\s*\n(?:\s+\S+:\s*(?:write|write-all)\b|\s+contents:\s*write\b)", content, re.I):
                findings["BROAD_PERMISSIONS"].append(rel)

    print("JANAVANI REPOSITORY HYGIENE AUDIT")
    print(f"Root: {root}")
    print("=" * 72)
    for category, items in findings.items():
        print(f"\n{category} ({len(items)})")
        for item in items:
            print(f"  - {item}")

    print("\nNo files were modified.")
    print("Interpret findings as review candidates; generated markers and TODOs are not automatically defects.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else "."))
