#!/usr/bin/env python3
"""Janavani repository hygiene audit.

Read-only, standard-library-only audit. Findings are review candidates, not
automatic deletion instructions.
"""
from __future__ import annotations

import hashlib
import re
import sys
from collections import defaultdict
from pathlib import Path

SKIP_DIRS = {".git", ".venv", "venv", "node_modules", "__pycache__", ".pytest_cache"}
TEXT_SUFFIXES = {".py", ".yml", ".yaml", ".toml", ".json", ".md", ".txt", ".sh", ".js", ".ts", ".tsx", ".jsx"}
CODE_SUFFIXES = {".py", ".js", ".ts", ".tsx", ".jsx", ".sh"}
PLACEHOLDER_RE = re.compile(r"(?:TODO|FIXME|NotImplementedError|IMPLEMENT_ME|PLACEHOLDER|YOUR_[_A-Z]+)")
GENERATED_RE = re.compile(r"(?:DO NOT EDIT|generated by|auto-generated|AUTOGENERATED)", re.I)
ACTION_RE = re.compile(r"uses:\s*([^\s#]+)")


def iter_files(root: Path):
    for path in root.rglob("*"):
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if path.is_file():
            yield path


def read_text(path: Path) -> str | None:
    if path.suffix.lower() not in TEXT_SUFFIXES:
        return None
    try:
        return path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return None


def normalized_code(content: str) -> str:
    lines = []
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        lines.append(re.sub(r"\s+", " ", stripped))
    return "\n".join(lines)


def main(root_arg: str = ".") -> int:
    root = Path(root_arg).resolve()
    findings: dict[str, list[str]] = defaultdict(list)
    contents: dict[str, str] = {}
    hashes: dict[str, list[str]] = defaultdict(list)

    for path in iter_files(root):
        rel = path.relative_to(root).as_posix()
        try:
            if path.stat().st_size == 0:
                findings["EMPTY"].append(rel)
                continue
        except OSError:
            continue
        content = read_text(path)
        if content is None:
            continue
        contents[rel] = content
        if not content.strip():
            findings["EMPTY"].append(rel)
            continue
        if PLACEHOLDER_RE.search(content):
            findings["PLACEHOLDER"].append(rel)
        if GENERATED_RE.search(content):
            findings["GENERATED"].append(rel)

        if rel.startswith(".github/workflows/"):
            for match in ACTION_RE.finditer(content):
                action = match.group(1)
                if "@" in action and not re.fullmatch(r"[0-9a-fA-F]{40}", action.rsplit("@", 1)[1]):
                    findings["MUTABLE_ACTION"].append(f"{rel}: {action}")
            if re.search(r"permissions:\s*\n(?:\s+\S+:\s*(?:write|write-all)\b|\s+contents:\s*write\b)", content, re.I):
                findings["BROAD_PERMISSIONS"].append(rel)

        if path.suffix.lower() in CODE_SUFFIXES:
            normalized = normalized_code(content)
            if len(normalized) >= 200:
                hashes[hashlib.sha256(normalized.encode()).hexdigest()].append(rel)

    for paths in hashes.values():
        if len(paths) > 1:
            findings["EXACT_DUPLICATE_CODE"].append(" | ".join(paths))

    searchable = "\n".join(contents.values())
    for rel, content in contents.items():
        path = Path(rel)
        if path.suffix != ".py" or not rel.startswith("scripts/"):
            continue
        if path.name.startswith("__") or path.name.startswith("test"):
            continue
        stem = path.stem
        references = sum(
            1 for other_rel in contents
            if other_rel != rel and (stem in contents[other_rel] or rel in contents[other_rel])
        )
        if references == 0:
            findings["POTENTIAL_ORPHAN_SCRIPT"].append(rel)

    print("JANAVANI REPOSITORY HYGIENE AUDIT")
    print(f"Root: {root}")
    print("=" * 72)
    for category in (
        "EMPTY", "PLACEHOLDER", "GENERATED", "EXACT_DUPLICATE_CODE",
        "POTENTIAL_ORPHAN_SCRIPT", "MUTABLE_ACTION", "BROAD_PERMISSIONS",
    ):
        items = findings.get(category, [])
        print(f"\n{category} ({len(items)})")
        for item in items:
            print(f"  - {item}")
    print("\nNo files were modified.")
    print("Duplicate/orphan results are conservative review candidates, not deletion instructions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else "."))
