EMAIL_ACK = (
    "Please acknowledge receipt of this email (electronic record) "
    "in accordance with Section 12(1) of the Information Technology Act, 2000, "
    "where applicable."
)

POST_ACK = (
    "Kindly acknowledge receipt of this communication."
)

HAND_ACK = (
    "Kindly acknowledge receipt by signing and dating the acknowledgement copy."
)

PORTAL_ACK = (
    "Please preserve the acknowledgement/reference number generated by the portal."
)
