name: Actionlint

on:
  pull_request:
  push:
    branches:
      - main
      - develop/**
      - refactor/**
      - cleanup/**

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: raven-actions/actionlint@v2
